### ISSUE TITLE
MoEngage v3.9.1 freezing application on start

### ISSUE THREAD

**Issue by rebann1990** [moengage/MoEngage-iOS-SDK#8] opened 2018-03-01 00:13 UTC
To preface, I admit that my using of MoEngage was incorrect. However, prior to 3.9.1, my improper usage still allowed the application to function like normal.

I had another analytic platform initialized in willFinishLaunchingWithOptions. Upon initializing that library, I update my user properties to reflect the new app launch, which also updates MoEngage's user at the same time with syncNow() being called at the end of the block of code setting my user values.

MoEngage was being initialized in didFinishLaunchingWithOptions. When MoEngage.sharedInstance().initializeDev(...) got called, the application would freeze, XCode would refuse to terminate the application and would also refuse to close itself, requiring me to Force Quit.

It wasn't only on initializeDev where the freeze would happen, but that's where timing had it occur most frequently. It seemed that any call to MoEngage's sharedInstance after the first "syncNow()" call would freeze the application, if that initial "syncNow()" call happened before we initialize the instance.

This was permitted before without issue. For at least six months I have been updating user properties on willFinishLaunchingWithOptions without odd behavior, despite the initialization being in didFinish. This is unique to v3.9.1 when disablePeriodicFlush() got introduced.

**Comment by ChengappaMoEngage** [comment] 2018-05-14 13:04
Closing as not able to reproduce.

**Closed by ChengappaMoEngage** 2018-05-14 13:04 UTC
